FROM python:3.8.2-slim-buster AS build

# virtualenv
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN python3 -m pip install --upgrade pip
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt


FROM python:3.8.2-slim-buster AS runtime

ARG USER_ID=1001
ENV USER_ID $USER_ID
ARG GROUP_ID=1001
ENV GROUP_ID $GROUP_ID
ARG APP_PATH=/mna_dashboard
ENV APP_PATH $APP_PATH
ARG APP_ID=ldag_app
ENV APP_ID $APP_ID

RUN groupadd --gid $GROUP_ID ${APP_ID} && \
    adduser ${APP_ID} --ingroup ${APP_ID} --gecos '' --disabled-password --uid ${USER_ID} && \
    mkdir -p ${APP_PATH} && \
    chown -R ${USER_ID}:${GROUP_ID} ${APP_PATH} &&\
    chown -R ${USER_ID}:${GROUP_ID} /home

COPY --chown=${USER_ID}:${GROUP_ID} --from=build /opt/venv /opt/venv
COPY --chown=${USER_ID}:${GROUP_ID} . ${APP_PATH}

WORKDIR ${APP_PATH}
USER ${APP_ID}
ENV PATH="/opt/venv/bin:$PATH"
# disables lag in stdout/stderr output
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

CMD streamlit run dashboard.py --server.port 7070
