# build stage
FROM node:10.15.0 as build-stage
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json ./
RUN npm install
RUN npm install -g @vue/cli
COPY . .
RUN npm run build

# production stage
FROM nginx:1.17.6
ARG UID=101 # built-in uid in nginx
ARG GID=101
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY --chown=${UID}:${GID} --from=build-stage /app/dist /usr/share/nginx/html 
RUN chown -R ${UID}:${GID} /var/cache/nginx && \
    chown -R ${UID}:${GID} /var/log/nginx && \
    chown -R ${UID}:${GID} /etc/nginx/conf.d
RUN touch /var/run/nginx.pid && \
    chown -R ${UID}:${GID} /var/run/nginx.pid
USER ${APP_ID}
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
