apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: # [PROJECT_NAME]
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: #[REGISTRY_URL]
    docker:
      dockerfile: Dockerfile

profiles:
  - name: dev
    deploy:
      kubectl:
        manifests:
        - # [PATH_TO_K8S_MANIFESTS]
        flags:
          global:
            - --namespace=mna-dashboard
  - name: stg
    deploy:
      kubectl:
        manifests:
        - # [PATH_TO_K8S_MANIFESTS]
        flags:
          global:
            - --namespace=mna-dashboard-stg
  - name: prod
    deploy:
      kubectl:
        manifests:
        - # [PATH_TO_K8S_MANIFESTS]
        flags:
          global:
            - --namespace=mna-dashboard
