apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: # [NS]
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      labels:
        component: redis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: false
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: # [NS]
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
