version: '3'
services:
    selenium:
      image: selenium/standalone-chrome-debug:3.141.59-20210607
      shm_size: 2gb
      ports:
        - 4444:4444
        - 5900:5900
      volumes:
        - #[path_to_host_folder]:[path_to_image_folder]
    dealogic-fetch:
      build:
        context: .
      depends_on:
        - selenium
      volumes:
        - #[path_to_host_folder]:[path_to_image_folder]